name: 'Crawl and deploy'

on:
  schedule:
  # 触发1： 定时触发：每天0:00,4:00,8:00,12:00,16:00,20:00执行定时任务，注意时间默认是国际标准时间，与国内相差有16个小时
    - cron: '0 0,4,8,12,16,20 * * *'
  # 触发2： 推送触发：排除路径，包含分支  
  push:
    paths-ignore:
      - 'json/version-position.json'
    branches:
      - master
jobs:
  crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: 'Get position by version'
        run: node version-position-crawler.js
      - name: 'Get position list'
        run: node position-crawler.js
      - name: 'Generate Finial JSON'
        run: node ver-pos-os-generator.js
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: json/version-position.json
          commit_message: 'feat: update JSON file'
          commit_user_name: vikyd
          commit_user_email: zwj_fhys@qq.com
      - name: 'Push to JSON repo'
        uses: crykn/copy_folder_to_another_repo_action@v1.0.6
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
        with:
          source_folder: 'json'
          destination_repo: 'fengzhao-notes/chromium-history-version-position'
          destination_folder: 'json'
          user_email: 'fengzhao1124@hotmail.com'
          user_name: 'fengzhao'
          commit_msg: 'feat: update JSON data'
      - name: 'Push to frontend repo'
        uses: crykn/copy_folder_to_another_repo_action@v1.0.6
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
        with:
          source_folder: 'json/ver-pos-os'
          destination_repo: 'fengzhao-notes/download-chromium-history-version-src'
          destination_folder: 'public/json/ver-pos-os'
          user_email: 'fengzhao1124@hotmail.com'
          user_name: 'fengzhao'
          commit_msg: 'feat: update JSON data'
  frontend:
    needs: crawler
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'fengzhao-notes/download-chromium-history-version-src'
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: 'Get not modify from github.io repo'
        run: curl https://raw.githubusercontent.com/fengzhao-notes/download-chromium-history-version/master/README.md --output dist/README.md
      - name: 'Push to github.io repo'
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
        with:
          source-directory: 'dist'
          destination-repository-name: 'download-chromium-history-version'
          target-branch: 'master'
          destination-github-username: 'fengzhao'
          user-email: 'fengzhao1124@hotmail.com'
          commit-message: 'feat: update JSON data'

